// @ts-nocheck
// this file is generated by farm-rust-plugin-auto-routes
// do not change anytime!
import React, { Suspense } from 'react';

function withLazyLoad(LazyComponent) {
  const lazyComponentWrapper = (props) => (
    <Suspense fallback={props.loadingComponent}>
      <LazyComponent {...props} />
    </Suspense>
  );
  return lazyComponentWrapper;
}

export const getRoutes = () => {
  const routes = {'home':{'path':'/home','requireLayout':true,'name':'Home','id':'home'},'home-me':{'path':'/home/me','id':'home-me','name':'home-me'},'404':{'name':'404','path':'/404','id':'404'},'logout':{'name':'logout','path':'/logout','id':'logout'},'login':{'name':'login','path':'/login','id':'login'}};
  return {
    routes,
    routeComponents: {
      'home': withLazyLoad(React.lazy(() => import('../pages/home/index.tsx'))),
      'home-me': withLazyLoad(React.lazy(() => import('../pages/home/me/index.tsx'))),
      '404': withLazyLoad(React.lazy(() => import('../pages/404.tsx'))),
      'logout': withLazyLoad(React.lazy(() => import('../pages/logout/index.tsx'))),
      'login': withLazyLoad(React.lazy(() => import('../pages/login/index.tsx')))
    },
  };
}
